### ISSUE TITLE
Start of function body without function header.

### ISSUE THREAD

**Issue by ukkiox** [openmultiplayer/omp-stdlib#1]
Hey, I just got my hands on this. Immediately after including I encountered an issue with `omp_object.inc` file.
It seems like somebody placed semicolon in place it shouldn't be(?).

```pawn
#if __namemax > 31
	native GetPlayerCameraTargetPlayerObject(playerid);
#else
	static stock __GetPlayerCameraTargetPlayerOb();
	{
	}
#endif
```
...this code throws an error which is mentioned in the title. After removing semicolon in line 4, `static stock __GetPlayerCameraTargetPlayerOb();` - issue goes away.

**Comment by iamkovshevoy** [comment]
You need to use compiler 3.10.11 from last windows build

**Comment by Y-Less** [comment]
While it is designed to work with the new compiler, it should still be possible to use the old ones.  It seems this was fixed a while ago.
