### ISSUE TITLE
error 025: function heading differs from prototype

### ISSUE THREAD

**Issue by Zorono** [openmultiplayer/omp-stdlib#12]
omp-stdlib is semi incompatible with samp-stdlib.... (**error 025: function heading differs from prototype**) because of those enumerations&tags and other changes such as color->colour and objectid->object and modelid->model and paintjobid->paintjob and componentid->component...
for example: https://github.com/NexiusTailer/Nex-AC/issues/285

**Comment by Y-Less** [comment]
Fixed.
