### ISSUE TITLE
References to not working SA-MP Forum/Wiki.

### ISSUE THREAD

**Issue by mrreus** [openmultiplayer/omp-stdlib#2]
https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_network.inc#L421
https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_network.inc#L422
https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_network.inc#L654
https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_network.inc#L655
https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_player.inc#L428
...

Likewise, another references can be found in other files.

**Comment by Y-Less** [comment]
A lot of these will need new links if you could help with finding them?
