### ISSUE TITLE
warning 202: number of arguments does not match definition

### ISSUE THREAD

**Issue by PazzOnee** [openmultiplayer/omp-stdlib#23]
**Native function have parameter for more argumetns, but when i put more arguments i got warning**

```
native bool:SendClientMessage(playerid, colour, const format[], OPEN_MP_TAGS:...); //no warning
SendClientMessage(playerid, -1, "Text %s %s", "test" , "test2");  //no warning

native bool:PlayerTextDrawSetString(playerid, PlayerText:textid, const format[], OPEN_MP_TAGS:...); //yes warning
PlayerTextDrawSetString(playerid, PlayerText:textid, "Test %s %s", "test", "test2"); //yes warning
```
there are many more such functions that give warnings and have the possibility of additional arguments

**Comment by shierru** [comment]
This is most likely a problem on your end, because I don't have this problem.

Perhaps you have PlayerTextDrawSetString overridden somewhere in your code and there are no variable arguments there.

**Comment by shierru** [comment]
For example, if you have a similar hook somewhere in your code where variable arguments are not taken into account, it will cause warning, as in your case.

```pawn
stock TEST_PlayerTextDrawSetString(playerid, PlayerText:text, const string[])
{
	return PlayerTextDrawSetString(playerid, text, string);
}
#if defined _ALS_PlayerTextDrawSetString
	#undef PlayerTextDrawSetString
#else
	#define _ALS_PlayerTextDrawSetString
#endif

#define PlayerTextDrawSetString TEST_PlayerTextDrawSetString
```

Example of warning playback:
```pawn
PlayerTextDrawSetString(playerid, PlayerText:-1, "Hello, World");

PlayerTextDrawSetString(playerid, PlayerText:-1, "Hello, %s", "World"); //  warning 202: number of arguments does not match definition

```

**Comment by PazzOnee** [comment]
Yes, weapon-config hooks make conflicts, they have check if open.mp is included to use native with tags, but that check don't working, i will open issue there. Thanks.
