### ISSUE TITLE
Deprecate GetPlayerObjectTarget

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/omp-stdlib#34]
## Issue
`GetPlayerObjectTarget` should be deprecated because `GetObjectTarget` is deprecated.

https://github.com/openmultiplayer/omp-stdlib/blob/085dfb13eb615955d89057c4564201b70786fee6/omp_object.inc#L1113

https://github.com/openmultiplayer/omp-stdlib/blob/085dfb13eb615955d89057c4564201b70786fee6/omp_object.inc#L1484-L1485

## Suggestion

```pawn
#pragma deprecated Use `GetPlayerObjectMovingTargetPos`
native Float:GetPlayerObjectTarget(playerid, objectid, &Float:targetX = 0.0, &Float:targetY = 0.0, &Float:targetZ = 0.0); 
```

**Comment by NexiusTailer** [comment]
Probably not relevant anymore since GetObjectTarget now is not deprecated
