### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by S0P4** [openmultiplayer/omp-stdlib#5]
On `OnPlayerEditAttachedObject` native, the docs page shows the old samp native, mean while the native was re-defined in this stdlib

[New native definition](https://github.com/openmultiplayer/omp-stdlib/blob/48bd2084568fe1b6483cb423eb162f95744aad9a/omp_object.inc#L1592)

[Old native definition](https://github.com/openmultiplayer/omp-stdlib/blob/b28f7b52d93e4472b11038caba10d78bdfb76729/documentation/readme-intermediate.md)

**Comment by Y-Less** [comment]
Fixed, thanks.
