### ISSUE TITLE
`LANDING_GEAR_STATE` enumeration is missing

### ISSUE THREAD

**Issue by Vince0789** [openmultiplayer/omp-stdlib#6]
`GetVehicleLandingGearState` returns a value with this tag, but the valid values are not specified. I'd create a PR myself but I don't know whether 0 is down and 1 is up or vice versa, and I don't currently have the means to test it.

https://github.com/openmultiplayer/omp-stdlib/blob/93a007a637929d65bb12905665450b62780f72bf/omp_vehicle.inc#L1213-L1217

**Comment by WoutProvost** [comment]
0 = gear down, 1 = gear up
