### ISSUE TITLE
CARLIGHT_REAR_BROKEN equals to 1024?

### ISSUE THREAD

**Issue by Mergevos** [openmultiplayer/omp-stdlib#9]
Whenever I set aforementioned one with `UpdateVehicleDamageStatus`, nothing happens, but when I use 64 instead it works correctly, and back lights shuts.

`UpdateVehicleDamageStatus(GetPlayerVehicleID(playerid), VEHICLE_PANEL_STATUS: 0, VEHICLE_DOOR_STATUS: 0, CARLIGHT_REAR_BROKEN, VEHICLE_TYRE_STATUS: 0);`

**Comment by WoutProvost** [comment]
Yes, it should be `64`, as is documented here: https://team.sa-mp.com/wiki/Light_States.html
